DROP TABLE IF EXISTS ANALYSIS.DM_RFM_SEGMENTS;
CREATE TABLE ANALYSIS.DM_RFM_SEGMENTS (
USER_ID INT4 NOT NULL,
RECENCY INT2 CHECK (RECENCY BETWEEN 1 AND 5),
FREQUENCY INT2 CHECK (FREQUENCY BETWEEN 1 AND 5),
MONETARY_VALUE INT2 CHECK (MONETARY_VALUE BETWEEN 1 AND 5),
CONSTRAINT USER_FK FOREIGN KEY (USER_ID)
REFERENCES PRODUCTION.USERS (ID)
);

INSERT INTO ANALYSIS.DM_RFM_SEGMENTS
SELECT R.USER_ID, RECENCY, FREQUENCY, MONETARY_VALUE
FROM ANALYSIS.TMP_RFM_RECENCY R
INNER JOIN ANALYSIS.TMP_RFM_FREQUENCY F ON R.USER_ID = F.USER_ID
INNER JOIN ANALYSIS.TMP_RFM_MONETARY_VALUE M ON M.USER_ID = F.USER_ID 

SELECT * FROM ANALYSIS.DM_RFM_SEGMENTS ORDER BY USER_ID ASC LIMIT 10
/*
"user_id" "recency" "frequency" "monetary_value"
0			1			3			4
1			4			3			3
2			2			3			5
3			2			3			3
4			4			3			3
5			5			5			5
6			1			3			5
7			4			2			2
8			1			1			3
9			1			3			2
*/
